export const labels = [
  { name: "normal", color: "bg-red-500" },
  { name: "fighting", color: "bg-pink-500" },
  { name: "flying", color: "bg-purple-500" },
  { name: "poison", color: "bg-indigo-500" },
  { name: "ground", color: "bg-blue-500" },
  { name: "rock", color: "bg-teal-500" },
  { name: "bug", color: "bg-green-500" },
  { name: "ghost", color: "bg-yellow-500" },
  { name: "steel", color: "bg-orange-500" },
  { name: "fire", color: "bg-red-600" },
  { name: "water", color: "bg-blue-600" },
  { name: "grass", color: "bg-green-600" },
  { name: "electric", color: "bg-yellow-600" },
  { name: "psychic", color: "bg-purple-600" },
  { name: "ice", color: "bg-cyan-500" },
  { name: "dragon", color: "bg-indigo-600" },
  { name: "dark", color: "bg-gray-700" },
  { name: "fairy", color: "bg-pink-600" },
  { name: "shadow", color: "bg-gray-500" },
];
